//
//  Currency+Country.swift
//  CurrencyConverter
//
//  Created by Abdul Wahab on 02/01/2024.
//

import Foundation

class CurrencyToCountryDatabase {
    func getFlagEmoji(forCurrencyCode currencyCode: String) -> String? {
        switch currencyCode {
        case "AED": return "🇦🇪"
        case "AFN": return "🇦🇫"
        case "ALL": return "🇦🇱"
        case "AMD": return "🇦🇲"
        case "ANG": return "🇦🇳"
        case "AOA": return "🇦🇴"
        case "ARS": return "🇦🇷"
        case "AUD": return "🇦🇺"
        case "AWG": return "🇦🇼"
        case "AZN": return "🇦🇿"
        case "BAM": return "🇧🇦"
        case "BBD": return "🇧🇧"
        case "BDT": return "🇧🇩"
        case "BGN": return "🇧🇬"
        case "BHD": return "🇧🇭"
        case "BIF": return "🇧🇮"
        case "BMD": return "🇧🇲"
        case "BND": return "🇧🇳"
        case "BOB": return "🇧🇴"
        case "BRL": return "🇧🇷"
        case "BSD": return "🇧🇸"
        case "BTC": return "₿"  // Bitcoin symbol
        case "BTN": return "🇧🇹"
        case "BWP": return "🇧🇼"
        case "BYN": return "🇧🇾"
        case "BZD": return "🇧🇿"
        case "CAD": return "🇨🇦"
        case "CDF": return "🇨🇩"
        case "CHF": return "🇨🇭"
        case "CLF": return "🇨🇱"
        case "CLP": return "🇨🇱"
        case "CNH": return "🇨🇳"
        case "CNY": return "🇨🇳"
        case "COP": return "🇨🇴"
        case "CRC": return "🇨🇷"
        case "CUC": return "🇨🇺"
        case "CUP": return "🇨🇺"
        case "CVE": return "🇨🇻"
        case "CZK": return "🇨🇿"
        case "DJF": return "🇩🇯"
        case "DKK": return "🇩🇰"
        case "DOP": return "🇩🇴"
        case "DZD": return "🇩🇿"
        case "EGP": return "🇪🇬"
        case "ERN": return "🇪🇷"
        case "ETB": return "🇪🇹"
        case "EUR": return "🇪🇺"
        case "FJD": return "🇫🇯"
        case "FKP": return "🇫🇰"
        case "GBP": return "🇬🇧"
        case "GEL": return "🇬🇪"
        case "GGP": return "🇬🇬"
        case "GHS": return "🇬🇭"
        case "GIP": return "🇬🇮"
        case "GMD": return "🇬🇲"
        case "GNF": return "🇬🇳"
        case "GTQ": return "🇬🇹"
        case "GYD": return "🇬🇾"
        case "HKD": return "🇭🇰"
        case "HNL": return "🇭🇳"
        case "HRK": return "🇭🇷"
        case "HTG": return "🇭🇹"
        case "HUF": return "🇭🇺"
        case "IDR": return "🇮🇩"
        case "ILS": return "🇮🇱"
        case "IMP": return "🇮🇲"
        case "INR": return "🇮🇳"
        case "IQD": return "🇮🇶"
        case "IRR": return "🇮🇷"
        case "ISK": return "🇮🇸"
        case "JEP": return "🇯🇪"
        case "JMD": return "🇯🇲"
        case "JOD": return "🇯🇴"
        case "JPY": return "🇯🇵"
        case "KES": return "🇰🇪"
        case "KGS": return "🇰🇬"
        case "KHR": return "🇰🇭"
        case "KMF": return "🇰🇲"
        case "KPW": return "🇰🇵"
        case "KRW": return "🇰🇷"
        case "KWD": return "🇰🇼"
        case "KYD": return "🇰🇾"
        case "KZT": return "🇰🇿"
        case "LAK": return "🇱🇦"
        case "LBP": return "🇱🇧"
        case "LKR": return "🇱🇰"
        case "LRD": return "🇱🇷"
        case "LSL": return "🇱🇸"
        case "LYD": return "🇱🇾"
        case "MAD": return "🇲🇦"
        case "MDL": return "🇲🇩"
        case "MGA": return "🇲🇬"
        case "MKD": return "🇲🇰"
        case "MMK": return "🇲🇲"
        case "MNT": return "🇲🇳"
        case "MOP": return "🇲🇴"
        case "MRU": return "🇲🇷"
        case "MUR": return "🇲🇺"
        case "MVR": return "🇲🇻"
        case "MWK": return "🇲🇼"
        case "MXN": return "🇲🇽"
        case "MYR": return "🇲🇾"
        case "MZN": return "🇲🇿"
        case "NAD": return "🇳🇦"
        case "NGN": return "🇳🇬"
        case "NIO": return "🇳🇮"
        case "NOK": return "🇳🇴"
        case "NPR": return "🇳🇵"
        case "NZD": return "🇳🇿"
        case "OMR": return "🇴🇲"
        case "PAB": return "🇵🇦"
        case "PEN": return "🇵🇪"
        case "PGK": return "🇵🇬"
        case "PHP": return "🇵🇭"
        case "PKR": return "🇵🇰"
        case "PLN": return "🇵🇱"
        case "PYG": return "🇵🇾"
        case "QAR": return "🇶🇦"
        case "RON": return "🇷🇴"
        case "RSD": return "🇷🇸"
        case "RUB": return "🇷🇺"
        case "RWF": return "🇷🇼"
        case "SAR": return "🇸🇦"
        case "SBD": return "🇸🇧"
        case "SCR": return "🇸🇨"
        case "SDG": return "🇸🇩"
        case "SEK": return "🇸🇪"
        case "SGD": return "🇸🇬"
        case "SHP": return "🇸🇭"
        case "SLL": return "🇸🇱"
        case "SOS": return "🇸🇴"
        case "SRD": return "🇸🇷"
        case "SSP": return "🇸🇸"
        case "STD": return "🇸🇹"
        case "STN": return "🇸🇹"
        case "SVC": return "🇸🇻"
        case "SYP": return "🇸🇾"
        case "SZL": return "🇸🇿"
        case "THB": return "🇹🇭"
        case "TJS": return "🇹🇯"
        case "TMT": return "🇹🇲"
        case "TND": return "🇹🇳"
        case "TOP": return "🇹🇴"
        case "TRY": return "🇹🇷"
        case "TTD": return "🇹🇹"
        case "TWD": return "🇹🇼"
        case "TZS": return "🇹🇿"
        case "UAH": return "🇺🇦"
        case "UGX": return "🇺🇬"
        case "USD": return "🇺🇸"
        case "UYU": return "🇺🇾"
        case "UZS": return "🇺🇿"
        case "VEF": return "🇻🇪"
        case "VES": return "🇻🇪"
        case "VND": return "🇻🇳"
        case "VUV": return "🇻🇺"
        case "WST": return "🇼🇸"
        case "XAF": return "🇨🇫"
        case "XAG": return "🥈"  // Silver symbol
        case "XAU": return "🥇"  // Gold symbol
        case "XCD": return "🇪🇨"
        case "XDR": return "📊"  // Bar Chart symbol
        case "XOF": return "🇧🇫"
        case "XPD": return "🏅"  // Medal symbol
        case "XPF": return "🇵🇫"
        case "XPT": return "🏆"  // Trophy symbol
        case "YER": return "🇾🇪"
        case "ZAR": return "🇿🇦"
        case "ZMW": return "🇿🇲"
        case "ZWL": return "🇿🇼"
        default: return nil
        }
    }
}
